server:
  port: 8820

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db:3306/docker_user_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root123456
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      filters: stat
      minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
      poolPreparedStatements: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
